import argparse
import csv
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple
_HF_CACHE: Dict[str, Any] = {}

SYSTEM_PROMPT = """You are an expert AI Evaluator specializing in Computer Vision and Natural Language Processing. Your task is to assess the quality of an image caption generated by an AI model (Candidate) by comparing it against a ground-truth reference (Reference).

Evaluation Criteria
Rate the Candidate Caption on a scale of 1 to 5 based on the following three criteria:

1. Accuracy (Truthfulness):
- Does the candidate describe the same objects and actions as the reference?
- Deduct points for hallucinations (mentioning things not in the reference) or incorrect attributes (wrong colors, wrong numbers).

2. Completeness (Coverage):
- Does the candidate capture all the essential elements mentioned in the reference?
- Deduct points if the candidate is too brief or misses key contextual details present in the ground truth.

3. Fluency (Linguistic Quality):
- Is the caption grammatically correct, easy to read, and natural-sounding?
- Deduct points for awkward phrasing, repetition, or syntax errors.

Scoring Rubric
- 5 (Excellent): Perfect alignment with the reference; no errors; natural phrasing.
- 4 (Good): Minor missing detail or slightly awkward phrasing, but factually correct.
- 3 (Fair): Correct main subject but misses significant details or has minor factual inaccuracies.
- 2 (Poor): Significant factual errors or very poor grammar; only partially related to the reference.
- 1 (Irrelevant): Completely wrong, hallucinations, or nonsensical.

Be a strict critic. Only award a 5 if the candidate is indistinguishable in quality from the reference.

Output Format
You must respond strictly in JSON format. Provide a brief reasoning for each score before stating the final number.

{
  "evaluation": {
    "accuracy": {
      "reasoning": "...",
      "score": 0
    },
    "completeness": {
      "reasoning": "...",
      "score": 0
    },
    "fluency": {
      "reasoning": "...",
      "score": 0
    }
  },
  "overall_summary": "...",
  "final_score_average": 0.0
}
"""

USER_PROMPT_TEMPLATE = """Reference Caption: {reference_caption}
Candidate Caption: {candidate_caption}
"""


def _find_latest_checkpoint(directory: str, prefix: str) -> str:
    dir_path = Path(directory)
    if not dir_path.is_dir():
        raise FileNotFoundError(f"Checkpoint directory not found: {directory}")

    latest_name = f"{prefix}_latest.pt"
    latest_path = dir_path / latest_name
    if latest_path.is_file():
        return str(latest_path)

    candidates = list(dir_path.glob(f"{prefix}-*.pt"))
    if not candidates:
        raise FileNotFoundError(
            f"No checkpoint found in {directory} for prefix '{prefix}'. "
            f"Expected {prefix}_latest.pt or {prefix}-XXX.pt"
        )

    def epoch_key(path: Path) -> int:
        match = re.search(r"-(\d+)\.pt$", path.name)
        return int(match.group(1)) if match else -1

    candidates.sort(key=epoch_key)
    return str(candidates[-1])


def _resolve_checkpoint(explicit_path: str, directory: str, prefix: str) -> str:
    if explicit_path:
        if not os.path.isfile(explicit_path):
            raise FileNotFoundError(f"Checkpoint not found: {explicit_path}")
        return explicit_path
    return _find_latest_checkpoint(directory=directory, prefix=prefix)


def _run_command(command: List[str], title: str) -> None:
    print(f"\n[RUN] {title}")
    print(" ".join(command))
    completed = subprocess.run(command, check=False, text=True, capture_output=True)
    if completed.stdout:
        print(completed.stdout)
    if completed.returncode != 0:
        if completed.stderr:
            print(completed.stderr, file=sys.stderr)
        raise RuntimeError(f"Command failed ({title}) with exit code {completed.returncode}")


def _tokenize(text: str) -> List[str]:
    return re.findall(r"[a-z0-9]+", text.lower())


def _select_reference(candidate: str, references: List[str], strategy: str) -> str:
    if not references:
        return ""
    if strategy == "first":
        return references[0]
    if strategy == "longest":
        return max(references, key=len)

    cand_tokens = set(_tokenize(candidate))
    if not cand_tokens:
        return references[0]

    best_ref = references[0]
    best_score = -1.0
    for ref in references:
        ref_tokens = set(_tokenize(ref))
        if not ref_tokens:
            score = 0.0
        else:
            score = len(cand_tokens & ref_tokens) / float(len(cand_tokens | ref_tokens))
        if score > best_score:
            best_score = score
            best_ref = ref
    return best_ref


def _extract_json(text: str) -> Optional[Dict[str, Any]]:
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return None
    try:
        return json.loads(text[start : end + 1])
    except json.JSONDecodeError:
        return None


def _coerce_float(value: Any) -> Optional[float]:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _build_messages(reference: str, candidate: str) -> List[Dict[str, str]]:
    user_prompt = USER_PROMPT_TEMPLATE.format(
        reference_caption=reference,
        candidate_caption=candidate,
    )
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt},
    ]


def _ensure_strict_json_messages(messages: List[Dict[str, str]], strict_json: bool) -> List[Dict[str, str]]:
    if not strict_json:
        return messages
    return [
        {"role": "system", "content": SYSTEM_PROMPT + "\nReturn only JSON. No extra text."},
        messages[1],
    ]


def _resolve_dtype(dtype_name: str):
    try:
        import torch
    except ImportError as exc:
        raise ImportError("PyTorch is required for hf_local provider. Install torch.") from exc

    name = dtype_name.lower()
    mapping = {
        "float16": torch.float16,
        "fp16": torch.float16,
        "bfloat16": torch.bfloat16,
        "bf16": torch.bfloat16,
        "float32": torch.float32,
        "fp32": torch.float32,
    }
    if name not in mapping:
        raise ValueError(f"Unsupported hf_dtype: {dtype_name}")
    return mapping[name]


def _load_hf_local_model(
    model_id: str,
    device: str,
    dtype_name: str,
    load_in_4bit: bool,
    load_in_8bit: bool,
    trust_remote_code: bool,
):
    try:
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
    except ImportError as exc:
        raise ImportError(
            "hf_local provider requires transformers and torch. Install: pip install transformers"
        ) from exc

    cache_key = "|".join([
        model_id,
        device,
        dtype_name,
        f"4bit={load_in_4bit}",
        f"8bit={load_in_8bit}",
        f"trc={trust_remote_code}",
    ])

    cached = _HF_CACHE.get("key") == cache_key
    if cached:
        return _HF_CACHE["tokenizer"], _HF_CACHE["model"], _HF_CACHE.get("use_device_map", False)

    dtype = _resolve_dtype(dtype_name)
    use_device_map = load_in_4bit or load_in_8bit or device == "auto"

    if use_device_map:
        try:
            import accelerate  # noqa: F401
        except ImportError as exc:
            raise RuntimeError(
                "accelerate is required for device_map/quantized loading. Install: pip install accelerate"
            ) from exc

    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True, trust_remote_code=trust_remote_code)
    if tokenizer.pad_token_id is None and tokenizer.eos_token_id is not None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    load_kwargs: Dict[str, Any] = {"trust_remote_code": trust_remote_code}
    if load_in_4bit or load_in_8bit:
        try:
            quant_config = BitsAndBytesConfig(
                load_in_4bit=load_in_4bit,
                load_in_8bit=load_in_8bit,
            )
            if load_in_4bit:
                if hasattr(quant_config, "bnb_4bit_quant_type"):
                    quant_config.bnb_4bit_quant_type = "nf4"
                if hasattr(quant_config, "bnb_4bit_use_double_quant"):
                    quant_config.bnb_4bit_use_double_quant = True
                if hasattr(quant_config, "bnb_4bit_compute_dtype"):
                    quant_config.bnb_4bit_compute_dtype = dtype
        except Exception as exc:
            raise RuntimeError(
                "Failed to build quantization config: "
                f"{exc}. Ensure transformers is up to date: pip install --upgrade transformers"
            ) from exc
        load_kwargs["quantization_config"] = quant_config
    if use_device_map:
        load_kwargs["device_map"] = "auto"
    else:
        load_kwargs["torch_dtype"] = dtype

    try:
        model = AutoModelForCausalLM.from_pretrained(model_id, **load_kwargs)
    except Exception as exc:
        if load_in_4bit or load_in_8bit:
            raise RuntimeError(
                "Failed to load quantized model: "
                f"{exc}. Ensure bitsandbytes + accelerate are installed and "
                "transformers is up to date."
            ) from exc
        raise

    if not use_device_map:
        model = model.to(device)
    model.eval()

    _HF_CACHE.clear()
    _HF_CACHE.update({"key": cache_key, "tokenizer": tokenizer, "model": model, "use_device_map": use_device_map})
    return tokenizer, model, use_device_map


def _build_hf_prompt(messages: List[Dict[str, str]], tokenizer) -> str:
    if hasattr(tokenizer, "apply_chat_template"):
        return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    parts = []
    for msg in messages:
        role = msg.get("role", "user")
        if role == "system":
            parts.append(f"System: {msg.get('content', '')}")
        elif role == "user":
            parts.append(f"User: {msg.get('content', '')}")
        else:
            parts.append(f"Assistant: {msg.get('content', '')}")
    parts.append("Assistant:")
    return "\n".join(parts)


def _call_llm_hf(
    model_id: str,
    device: str,
    dtype_name: str,
    load_in_4bit: bool,
    load_in_8bit: bool,
    trust_remote_code: bool,
    temperature: float,
    max_tokens: int,
    messages: List[Dict[str, str]],
    strict_json: bool,
) -> str:
    try:
        import torch
    except ImportError as exc:
        raise ImportError("PyTorch is required for hf_local provider. Install torch.") from exc

    messages = _ensure_strict_json_messages(messages, strict_json)

    tokenizer, model, use_device_map = _load_hf_local_model(
        model_id=model_id,
        device=device,
        dtype_name=dtype_name,
        load_in_4bit=load_in_4bit,
        load_in_8bit=load_in_8bit,
        trust_remote_code=trust_remote_code,
    )

    prompt = _build_hf_prompt(messages, tokenizer)
    inputs = tokenizer(prompt, return_tensors="pt")
    if use_device_map:
        embed_device = model.get_input_embeddings().weight.device
        input_ids = inputs["input_ids"].to(embed_device)
        attention_mask = inputs.get("attention_mask")
        if attention_mask is not None:
            attention_mask = attention_mask.to(embed_device)
    else:
        input_ids = inputs["input_ids"].to(model.device)
        attention_mask = inputs.get("attention_mask")
        if attention_mask is not None:
            attention_mask = attention_mask.to(model.device)

    do_sample = temperature > 0.0
    generate_kwargs: Dict[str, Any] = {
        "max_new_tokens": max_tokens,
        "do_sample": do_sample,
        "pad_token_id": tokenizer.pad_token_id or tokenizer.eos_token_id,
        "eos_token_id": tokenizer.eos_token_id,
    }
    if do_sample:
        generate_kwargs["temperature"] = temperature

    with torch.inference_mode():
        outputs = model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)

    output_ids = outputs[0][input_ids.shape[-1] :]
    return tokenizer.decode(output_ids, skip_special_tokens=True).strip()


def _call_llm_hf_batch(
    model_id: str,
    device: str,
    dtype_name: str,
    load_in_4bit: bool,
    load_in_8bit: bool,
    trust_remote_code: bool,
    temperature: float,
    max_tokens: int,
    message_batches: List[List[Dict[str, str]]],
    strict_json: bool,
) -> List[str]:
    try:
        import torch
    except ImportError as exc:
        raise ImportError("PyTorch is required for hf_local provider. Install torch.") from exc

    tokenizer, model, use_device_map = _load_hf_local_model(
        model_id=model_id,
        device=device,
        dtype_name=dtype_name,
        load_in_4bit=load_in_4bit,
        load_in_8bit=load_in_8bit,
        trust_remote_code=trust_remote_code,
    )

    prompts = []
    for messages in message_batches:
        messages = _ensure_strict_json_messages(messages, strict_json)
        prompts.append(_build_hf_prompt(messages, tokenizer))

    inputs = tokenizer(prompts, return_tensors="pt", padding=True)
    input_ids = inputs["input_ids"]
    attention_mask = inputs.get("attention_mask")
    if attention_mask is None:
        attention_mask = input_ids.ne(tokenizer.pad_token_id or 0).long()

    if use_device_map:
        embed_device = model.get_input_embeddings().weight.device
        input_ids = input_ids.to(embed_device)
        attention_mask = attention_mask.to(embed_device)
    else:
        input_ids = input_ids.to(model.device)
        attention_mask = attention_mask.to(model.device)

    do_sample = temperature > 0.0
    generate_kwargs: Dict[str, Any] = {
        "max_new_tokens": max_tokens,
        "do_sample": do_sample,
        "pad_token_id": tokenizer.pad_token_id or tokenizer.eos_token_id,
        "eos_token_id": tokenizer.eos_token_id,
    }
    if do_sample:
        generate_kwargs["temperature"] = temperature

    with torch.inference_mode():
        outputs = model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)

    input_lengths = attention_mask.sum(dim=1).tolist()
    responses = []
    for idx, output in enumerate(outputs):
        start = int(input_lengths[idx])
        output_ids = output[start:]
        responses.append(tokenizer.decode(output_ids, skip_special_tokens=True).strip())

    return responses


def _call_llm(
    model: str,
    temperature: float,
    max_tokens: int,
    strict_json: bool,
    messages: List[Dict[str, str]],
    hf_device: str,
    hf_dtype: str,
    hf_load_in_4bit: bool,
    hf_load_in_8bit: bool,
    hf_trust_remote_code: bool,
) -> str:
    return _call_llm_hf(
        model_id=model,
        device=hf_device,
        dtype_name=hf_dtype,
        load_in_4bit=hf_load_in_4bit,
        load_in_8bit=hf_load_in_8bit,
        trust_remote_code=hf_trust_remote_code,
        temperature=temperature,
        max_tokens=max_tokens,
        messages=messages,
        strict_json=strict_json,
    )


def judge_caption(
    model: str,
    temperature: float,
    max_tokens: int,
    strict_json: bool,
    max_retries: int,
    reference: str,
    candidate: str,
    hf_device: str,
    hf_dtype: str,
    hf_load_in_4bit: bool,
    hf_load_in_8bit: bool,
    hf_trust_remote_code: bool,
) -> Tuple[Optional[Dict[str, Any]], str]:
    messages = _build_messages(reference, candidate)
    last_response = ""

    for attempt in range(max_retries + 1):
        if attempt > 0:
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT + "\nReturn only JSON. No extra text."},
                {"role": "user", "content": messages[1]["content"]},
            ]

        try:
            last_response = _call_llm(
                model=model,
                temperature=temperature,
                max_tokens=max_tokens,
                strict_json=strict_json,
                messages=messages,
                hf_device=hf_device,
                hf_dtype=hf_dtype,
                hf_load_in_4bit=hf_load_in_4bit,
                hf_load_in_8bit=hf_load_in_8bit,
                hf_trust_remote_code=hf_trust_remote_code,
            )
        except (ValueError, RuntimeError, ImportError) as exc:
            return None, f"LLM request failed: {exc}"

        parsed = _extract_json(last_response)
        if parsed is not None:
            return parsed, ""

    return None, "Failed to parse JSON from LLM response"


def judge_caption_batch(
    model: str,
    temperature: float,
    max_tokens: int,
    strict_json: bool,
    max_retries: int,
    references: List[str],
    candidates: List[str],
    hf_device: str,
    hf_dtype: str,
    hf_load_in_4bit: bool,
    hf_load_in_8bit: bool,
    hf_trust_remote_code: bool,
) -> List[Tuple[Optional[Dict[str, Any]], str]]:
    message_batches = [_build_messages(ref, cand) for ref, cand in zip(references, candidates)]

    try:
        responses = _call_llm_hf_batch(
            model_id=model,
            device=hf_device,
            dtype_name=hf_dtype,
            load_in_4bit=hf_load_in_4bit,
            load_in_8bit=hf_load_in_8bit,
            trust_remote_code=hf_trust_remote_code,
            temperature=temperature,
            max_tokens=max_tokens,
            message_batches=message_batches,
            strict_json=strict_json,
        )
    except (ValueError, RuntimeError, ImportError) as exc:
        return [(None, f"LLM request failed: {exc}")] * len(references)

    results: List[Tuple[Optional[Dict[str, Any]], str]] = []
    for response in responses:
        parsed = _extract_json(response)
        if parsed is not None:
            results.append((parsed, ""))
        else:
            results.append((None, "Failed to parse JSON from LLM response"))

    for idx, (parsed, _) in enumerate(results):
        if parsed is None:
            retry_result, retry_error = judge_caption(
                model=model,
                temperature=temperature,
                max_tokens=max_tokens,
                strict_json=strict_json,
                max_retries=max_retries,
                reference=references[idx],
                candidate=candidates[idx],
                hf_device=hf_device,
                hf_dtype=hf_dtype,
                hf_load_in_4bit=hf_load_in_4bit,
                hf_load_in_8bit=hf_load_in_8bit,
                hf_trust_remote_code=hf_trust_remote_code,
            )
            results[idx] = (retry_result, retry_error)

    return results


def _load_predictions(json_path: str) -> Tuple[Dict[str, List[str]], Dict[str, List[str]]]:
    with open(json_path, "r", encoding="utf-8") as f:
        payload = json.load(f)
    return payload.get("predictions", {}), payload.get("references", {})


def _load_existing_judgments(path: str) -> Dict[str, Dict[str, Any]]:
    if not os.path.isfile(path):
        return {}
    results: Dict[str, Dict[str, Any]] = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue
            image_id = str(record.get("image_id", ""))
            if image_id:
                results[image_id] = record
    return results


def _save_judgment_line(path: str, record: Dict[str, Any]) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=True) + "\n")


def _aggregate_scores(records: Iterable[Dict[str, Any]]) -> Dict[str, Any]:
    totals = {"accuracy": 0.0, "completeness": 0.0, "fluency": 0.0, "final": 0.0}
    count = 0
    errors = 0

    for record in records:
        evaluation = record.get("evaluation", {})
        acc = _coerce_float(evaluation.get("accuracy", {}).get("score"))
        comp = _coerce_float(evaluation.get("completeness", {}).get("score"))
        flu = _coerce_float(evaluation.get("fluency", {}).get("score"))
        final = _coerce_float(record.get("final_score_average"))
        if None in (acc, comp, flu):
            errors += 1
            continue
        if final is None:
            final = (acc + comp + flu) / 3.0
        totals["accuracy"] += acc
        totals["completeness"] += comp
        totals["fluency"] += flu
        totals["final"] += final
        count += 1

    averages = {
        "accuracy_avg": totals["accuracy"] / count if count else 0.0,
        "completeness_avg": totals["completeness"] / count if count else 0.0,
        "fluency_avg": totals["fluency"] / count if count else 0.0,
        "final_score_avg": totals["final"] / count if count else 0.0,
        "num_scored": count,
        "num_errors": errors,
    }
    return averages


def _save_summary_csv(path: str, summary: Dict[str, Dict[str, Dict[str, Any]]]) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "dataset",
            "mode",
            "num_scored",
            "num_errors",
            "accuracy_avg",
            "completeness_avg",
            "fluency_avg",
            "final_score_avg",
        ])
        for dataset_name, modes in summary.items():
            for mode, metrics in modes.items():
                writer.writerow([
                    dataset_name,
                    mode,
                    metrics.get("num_scored", 0),
                    metrics.get("num_errors", 0),
                    f"{metrics.get('accuracy_avg', 0.0):.4f}",
                    f"{metrics.get('completeness_avg', 0.0):.4f}",
                    f"{metrics.get('fluency_avg', 0.0):.4f}",
                    f"{metrics.get('final_score_avg', 0.0):.4f}",
                ])


def _build_eval_jobs(args: argparse.Namespace, dataset: Dict[str, str]) -> List[Dict[str, Any]]:
    ckpt_cnn = _resolve_checkpoint(dataset.get("ckpt_cnn", ""), dataset["cnn_dir"], dataset["cnn_prefix"])
    ckpt_mlp = _resolve_checkpoint(dataset.get("ckpt_mlp", ""), dataset["mlp_dir"], dataset["mlp_prefix"])
    ckpt_tf = _resolve_checkpoint(dataset.get("ckpt_transformer", ""), dataset["transformer_dir"], dataset["transformer_prefix"])
    ckpt_ft = _resolve_checkpoint(dataset.get("ckpt_finetune", ""), dataset["finetune_dir"], dataset["finetune_prefix"])

    return [
        {
            "mode": "cnn_rnn",
            "args": [
                "--model_arch", "cnn_rnn",
                "--checkpoint", ckpt_cnn,
                "--images_dir", dataset["images_dir"],
                "--captions_file", dataset["captions_file"],
                "--device", args.device,
                "--max_samples", str(args.max_samples),
                "--temperature", str(args.temperature),
                "--cnn_max_len", str(args.cnn_max_len),
            ],
        },
        {
            "mode": "mlp",
            "args": [
                "--model_arch", "clipcap",
                "--data", dataset["data"],
                "--checkpoint", ckpt_mlp,
                "--mapping_type", "mlp",
                "--only_prefix",
                "--prefix_length", str(args.prefix_length),
                "--prefix_length_clip", str(args.prefix_length_clip),
                "--num_layers", str(args.num_layers),
                "--decode", args.decode,
                "--beam_size", str(args.beam_size),
                "--top_p", str(args.top_p),
                "--temperature", str(args.temperature),
                "--entry_length", str(args.entry_length),
                "--device", args.device,
                "--max_samples", str(args.max_samples),
            ],
        },
        {
            "mode": "transformer",
            "args": [
                "--model_arch", "clipcap",
                "--data", dataset["data"],
                "--checkpoint", ckpt_tf,
                "--mapping_type", "transformer",
                "--only_prefix",
                "--prefix_length", str(args.prefix_length),
                "--prefix_length_clip", str(args.prefix_length_clip),
                "--num_layers", str(args.num_layers),
                "--decode", args.decode,
                "--beam_size", str(args.beam_size),
                "--top_p", str(args.top_p),
                "--temperature", str(args.temperature),
                "--entry_length", str(args.entry_length),
                "--device", args.device,
                "--max_samples", str(args.max_samples),
            ],
        },
        {
            "mode": "finetune",
            "args": [
                "--model_arch", "clipcap",
                "--data", dataset["data"],
                "--checkpoint", ckpt_ft,
                "--mapping_type", "transformer",
                "--prefix_length", str(args.prefix_length),
                "--prefix_length_clip", str(args.prefix_length_clip),
                "--num_layers", str(args.num_layers),
                "--decode", args.decode,
                "--beam_size", str(args.beam_size),
                "--top_p", str(args.top_p),
                "--temperature", str(args.temperature),
                "--entry_length", str(args.entry_length),
                "--device", args.device,
                "--max_samples", str(args.max_samples),
            ],
        },
    ]


def _resolve_eval_json(
    eval_json: str,
    dataset: Dict[str, str],
    mode: str,
) -> Tuple[str, bool]:
    if os.path.isfile(eval_json):
        return eval_json, False

    fallback_map = {
        "cnn_rnn": os.path.join(dataset["cnn_dir"], "eval_results.json"),
        "mlp": os.path.join(dataset["mlp_dir"], "eval_results.json"),
        "transformer": os.path.join(dataset["transformer_dir"], "eval_results.json"),
        "finetune": os.path.join(dataset["finetune_dir"], "eval_results.json"),
    }
    fallback = fallback_map.get(mode, "")
    if fallback and os.path.isfile(fallback):
        return fallback, True

    return eval_json, False


def _replace_arg_value(args_list: List[str], flag: str, value: Any) -> List[str]:
    updated = list(args_list)
    if flag in updated:
        idx = updated.index(flag)
        if idx + 1 < len(updated):
            updated[idx + 1] = str(value)
            return updated
    return updated + [flag, str(value)]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run LLM-judge evaluation for 4 modes on Flickr30k and MSCOCO in one command."
    )
    parser.add_argument("--python_exec", default=sys.executable)
    parser.add_argument("--evaluate_script", default="./evaluate.py")
    parser.add_argument("--out_dir", default="./checkpoints/llm_judge")

    parser.add_argument("--datasets", default="all", choices=["all", "flickr30k", "mscoco"])

    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--max_samples", type=int, default=0)
    parser.add_argument("--temperature", type=float, default=1.0)

    parser.add_argument("--decode", default="beam", choices=["beam", "nucleus"])
    parser.add_argument("--beam_size", type=int, default=5)
    parser.add_argument("--top_p", type=float, default=0.8)
    parser.add_argument("--entry_length", type=int, default=67)
    parser.add_argument("--cnn_max_len", type=int, default=30)

    parser.add_argument("--prefix_length", type=int, default=10)
    parser.add_argument("--prefix_length_clip", type=int, default=10)
    parser.add_argument("--num_layers", type=int, default=8)

    parser.add_argument("--force_regen", action="store_true")
    parser.add_argument("--judge_only", action="store_true")

    parser.add_argument("--model", default="meta-llama/Meta-Llama-3.1-8B-Instruct")
    parser.add_argument("--judge_temperature", type=float, default=0.0)
    parser.add_argument("--judge_max_tokens", type=int, default=256)
    parser.add_argument("--judge_batch_size", type=int, default=1)
    parser.add_argument("--judge_delay", type=float, default=0.0)
    parser.add_argument("--judge_retries", type=int, default=2)
    parser.add_argument("--force_judge", action="store_true")
    parser.add_argument("--strict_json", action="store_true")
    parser.add_argument("--reference_strategy", default="best_overlap", choices=["best_overlap", "first", "longest"])
    parser.add_argument("--hf_device", default="cuda:0")
    parser.add_argument("--hf_dtype", default="float16")
    parser.add_argument("--hf_load_in_4bit", action="store_true")
    parser.add_argument("--hf_load_in_8bit", action="store_true")
    parser.add_argument("--hf_trust_remote_code", action="store_true")

    parser.add_argument("--flickr_data", default="./data/flickr30k/flickr30k_clip_ViT-B_32_test.pkl")
    parser.add_argument("--flickr_images_dir", default="./flickr-image-dataset/flickr30k_images/flickr30k_images")
    parser.add_argument("--flickr_captions_file", default="./data/flickr30k/results_test.csv")
    parser.add_argument("--flickr_cnn_dir", default="./checkpoints/cnn_rnn")
    parser.add_argument("--flickr_cnn_prefix", default="flickr30k_cnn_rnn")
    parser.add_argument("--flickr_mlp_dir", default="./checkpoints/flickr30k_mlp")
    parser.add_argument("--flickr_mlp_prefix", default="flickr30k_mlp")
    parser.add_argument("--flickr_transformer_dir", default="./checkpoints/flickr30k_transformer_frozen")
    parser.add_argument("--flickr_transformer_prefix", default="flickr30k_transformer_frozen")
    parser.add_argument("--flickr_finetune_dir", default="./checkpoints/flickr30k_transformer_finetune")
    parser.add_argument("--flickr_finetune_prefix", default="flickr30k_transformer_finetune")
    parser.add_argument("--ckpt_flickr_cnn", default="")
    parser.add_argument("--ckpt_flickr_mlp", default="")
    parser.add_argument("--ckpt_flickr_transformer", default="")
    parser.add_argument("--ckpt_flickr_finetune", default="")

    parser.add_argument("--mscoco_data", default="./data/mscoco/mscoco_clip_ViT-B_32_val.pkl")
    parser.add_argument("--mscoco_images_dir", default="./data/mscoco/val2017")
    parser.add_argument("--mscoco_captions_file", default="./data/mscoco/results_val.csv")
    parser.add_argument("--mscoco_cnn_dir", default="./checkpoints/mscoco_cnn_rnn")
    parser.add_argument("--mscoco_cnn_prefix", default="mscoco_cnn_rnn")
    parser.add_argument("--mscoco_mlp_dir", default="./checkpoints/mscoco_mlp")
    parser.add_argument("--mscoco_mlp_prefix", default="mscoco_mlp")
    parser.add_argument("--mscoco_transformer_dir", default="./checkpoints/mscoco_transformer_frozen")
    parser.add_argument("--mscoco_transformer_prefix", default="mscoco_transformer_frozen")
    parser.add_argument("--mscoco_finetune_dir", default="./checkpoints/mscoco_transformer_finetune")
    parser.add_argument("--mscoco_finetune_prefix", default="mscoco_transformer_finetune")
    parser.add_argument("--ckpt_mscoco_cnn", default="")
    parser.add_argument("--ckpt_mscoco_mlp", default="")
    parser.add_argument("--ckpt_mscoco_transformer", default="")
    parser.add_argument("--ckpt_mscoco_finetune", default="")

    args = parser.parse_args()

    if args.hf_load_in_4bit and args.hf_load_in_8bit:
        raise ValueError("Only one of --hf_load_in_4bit or --hf_load_in_8bit can be set")
    if args.judge_only and args.force_regen:
        raise ValueError("--judge_only cannot be used with --force_regen")
    if args.judge_batch_size < 1:
        raise ValueError("--judge_batch_size must be >= 1")

    if not os.path.isfile(args.evaluate_script):
        raise FileNotFoundError(f"evaluate script not found: {args.evaluate_script}")

    datasets: List[Dict[str, str]] = []
    if args.datasets in ("all", "flickr30k"):
        datasets.append(
            {
                "name": "flickr30k",
                "data": args.flickr_data,
                "images_dir": args.flickr_images_dir,
                "captions_file": args.flickr_captions_file,
                "cnn_dir": args.flickr_cnn_dir,
                "cnn_prefix": args.flickr_cnn_prefix,
                "mlp_dir": args.flickr_mlp_dir,
                "mlp_prefix": args.flickr_mlp_prefix,
                "transformer_dir": args.flickr_transformer_dir,
                "transformer_prefix": args.flickr_transformer_prefix,
                "finetune_dir": args.flickr_finetune_dir,
                "finetune_prefix": args.flickr_finetune_prefix,
                "ckpt_cnn": args.ckpt_flickr_cnn,
                "ckpt_mlp": args.ckpt_flickr_mlp,
                "ckpt_transformer": args.ckpt_flickr_transformer,
                "ckpt_finetune": args.ckpt_flickr_finetune,
            }
        )

    if args.datasets in ("all", "mscoco"):
        datasets.append(
            {
                "name": "mscoco",
                "data": args.mscoco_data,
                "images_dir": args.mscoco_images_dir,
                "captions_file": args.mscoco_captions_file,
                "cnn_dir": args.mscoco_cnn_dir,
                "cnn_prefix": args.mscoco_cnn_prefix,
                "mlp_dir": args.mscoco_mlp_dir,
                "mlp_prefix": args.mscoco_mlp_prefix,
                "transformer_dir": args.mscoco_transformer_dir,
                "transformer_prefix": args.mscoco_transformer_prefix,
                "finetune_dir": args.mscoco_finetune_dir,
                "finetune_prefix": args.mscoco_finetune_prefix,
                "ckpt_cnn": args.ckpt_mscoco_cnn,
                "ckpt_mlp": args.ckpt_mscoco_mlp,
                "ckpt_transformer": args.ckpt_mscoco_transformer,
                "ckpt_finetune": args.ckpt_mscoco_finetune,
            }
        )

    summary: Dict[str, Dict[str, Dict[str, Any]]] = {}

    for dataset in datasets:
        dataset_name = dataset["name"]
        dataset_out_dir = os.path.join(args.out_dir, dataset_name)
        os.makedirs(dataset_out_dir, exist_ok=True)

        jobs = _build_eval_jobs(args, dataset)

        summary[dataset_name] = {}

        for job in jobs:
            mode = job["mode"]
            eval_json = os.path.join(dataset_out_dir, f"eval_{mode}.json")
            judge_path = os.path.join(dataset_out_dir, f"llm_judge_{mode}.jsonl")

            if args.judge_only and not args.force_judge:
                existing_early = _load_existing_judgments(judge_path)
                if existing_early:
                    metrics = _aggregate_scores(existing_early.values())
                    summary[dataset_name][mode] = metrics
                    print(
                        f"[SKIP] LLM judge already exists for {dataset_name} {mode} "
                        f"(n={metrics['num_scored']}, errors={metrics['num_errors']})"
                    )
                    continue

            if args.judge_only:
                eval_json, used_fallback = _resolve_eval_json(eval_json, dataset, mode)
                if not os.path.isfile(eval_json):
                    if dataset_name == "mscoco":
                        auto_samples = args.max_samples if args.max_samples > 0 else 200
                        command = [
                            args.python_exec,
                            args.evaluate_script,
                            *_replace_arg_value(job["args"], "--max_samples", auto_samples),
                            "--save_predictions",
                            eval_json,
                        ]
                        _run_command(command, title=f"Evaluate {dataset_name} {mode} (auto {auto_samples})")
                    if not os.path.isfile(eval_json):
                        raise FileNotFoundError(
                            f"Missing eval JSON for {dataset_name} {mode}. "
                            f"Expected: {eval_json}"
                        )
                note = " (fallback)" if used_fallback else ""
                print(f"\n[SKIP] Using existing predictions for {dataset_name} {mode}: {eval_json}{note}")
            else:
                if args.force_regen or not os.path.isfile(eval_json):
                    command = [
                        args.python_exec,
                        args.evaluate_script,
                        *job["args"],
                        "--save_predictions",
                        eval_json,
                    ]
                    _run_command(command, title=f"Evaluate {dataset_name} {mode}")
                else:
                    print(f"\n[SKIP] Using existing predictions for {dataset_name} {mode}: {eval_json}")

            predictions, references = _load_predictions(eval_json)
            image_ids = sorted(predictions.keys())

            if args.max_samples > 0:
                image_ids = image_ids[: args.max_samples]

            if args.force_judge and os.path.isfile(judge_path):
                os.remove(judge_path)
            existing = {} if args.force_judge else _load_existing_judgments(judge_path)

            if not args.force_judge and existing:
                scored = sum(1 for image_id in image_ids if image_id in existing)
                if scored >= len(image_ids):
                    print(f"[SKIP] LLM judge already complete for {dataset_name} {mode} ({scored} samples)")
                    all_records = _load_existing_judgments(judge_path)
                    metrics = _aggregate_scores(all_records.values())
                    summary[dataset_name][mode] = metrics
                    print(
                        f"{dataset_name} {mode} -> final_avg={metrics['final_score_avg']:.4f} "
                        f"(n={metrics['num_scored']}, errors={metrics['num_errors']})"
                    )
                    continue

            batch_ids: List[str] = []
            batch_refs: List[str] = []
            batch_cands: List[str] = []

            def flush_batch() -> None:
                if not batch_ids:
                    return
                if args.judge_batch_size == 1:
                    for image_id, reference, candidate in zip(batch_ids, batch_refs, batch_cands):
                        result, error = judge_caption(
                            model=args.model,
                            temperature=args.judge_temperature,
                            max_tokens=args.judge_max_tokens,
                            strict_json=args.strict_json,
                            max_retries=args.judge_retries,
                            reference=reference,
                            candidate=candidate,
                            hf_device=args.hf_device,
                            hf_dtype=args.hf_dtype,
                            hf_load_in_4bit=args.hf_load_in_4bit,
                            hf_load_in_8bit=args.hf_load_in_8bit,
                            hf_trust_remote_code=args.hf_trust_remote_code,
                        )
                        record = {
                            "image_id": image_id,
                            "reference": reference,
                            "candidate": candidate,
                            "evaluation": result.get("evaluation") if result else {},
                            "overall_summary": result.get("overall_summary") if result else "",
                            "final_score_average": result.get("final_score_average") if result else None,
                            "error": error,
                        }
                        _save_judgment_line(judge_path, record)
                else:
                    results = judge_caption_batch(
                        model=args.model,
                        temperature=args.judge_temperature,
                        max_tokens=args.judge_max_tokens,
                        strict_json=args.strict_json,
                        max_retries=args.judge_retries,
                        references=batch_refs,
                        candidates=batch_cands,
                        hf_device=args.hf_device,
                        hf_dtype=args.hf_dtype,
                        hf_load_in_4bit=args.hf_load_in_4bit,
                        hf_load_in_8bit=args.hf_load_in_8bit,
                        hf_trust_remote_code=args.hf_trust_remote_code,
                    )
                    for image_id, reference, candidate, (result, error) in zip(
                        batch_ids, batch_refs, batch_cands, results
                    ):
                        record = {
                            "image_id": image_id,
                            "reference": reference,
                            "candidate": candidate,
                            "evaluation": result.get("evaluation") if result else {},
                            "overall_summary": result.get("overall_summary") if result else "",
                            "final_score_average": result.get("final_score_average") if result else None,
                            "error": error,
                        }
                        _save_judgment_line(judge_path, record)

                batch_ids.clear()
                batch_refs.clear()
                batch_cands.clear()

                if args.judge_delay > 0:
                    time.sleep(args.judge_delay)

            for image_id in image_ids:
                if image_id in existing:
                    continue
                if image_id not in references:
                    continue

                candidate = predictions[image_id][0] if predictions.get(image_id) else ""
                reference_list = references.get(image_id, [])
                reference = _select_reference(candidate, reference_list, args.reference_strategy)

                batch_ids.append(image_id)
                batch_refs.append(reference)
                batch_cands.append(candidate)

                if len(batch_ids) >= args.judge_batch_size:
                    flush_batch()

            flush_batch()

            all_records = _load_existing_judgments(judge_path)
            metrics = _aggregate_scores(all_records.values())
            summary[dataset_name][mode] = metrics

            print(
                f"{dataset_name} {mode} -> final_avg={metrics['final_score_avg']:.4f} "
                f"(n={metrics['num_scored']}, errors={metrics['num_errors']})"
            )

    summary_json = os.path.join(args.out_dir, "llm_judge_summary.json")
    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=True, indent=2)

    summary_csv = os.path.join(args.out_dir, "llm_judge_summary.csv")
    _save_summary_csv(summary_csv, summary)

    print(f"\nSaved: {summary_json}")
    print(f"Saved: {summary_csv}")


if __name__ == "__main__":
    main()
